package com.se325.common;

// default package
// Generated 16/09/2013 3:07:40 AM by Hibernate Tools 4.0.0

/**
 * ReplayUserId generated by hbm2java
 */
public class ReplayUser implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int id;
    private int matchId;
    private long steamId64;

    public ReplayUser() {
    }

    public ReplayUser(int id, int matchId, long steamId64) {
        this.id = id;
        this.matchId = matchId;
        this.steamId64 = steamId64;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getMatchId() {
        return this.matchId;
    }

    public void setMatchId(int matchId) {
        this.matchId = matchId;
    }

    public long getSteamId64() {
        return this.steamId64;
    }

    public void setSteamId64(long steamId64) {
        this.steamId64 = steamId64;
    }
}
