package com.se325.common;

import org.hibernate.annotations.Entity;

// default package
// Generated 19/09/2013 3:18:21 AM by Hibernate Tools 4.0.0

/**
 * ReplayUser generated by hbm2java
 */

@Entity
public class ReplayUser implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private int matchId;
    private long steamId64;

    public ReplayUser() {
    }

    public ReplayUser(int matchId, long steamId64) {
        this.matchId = matchId;
        this.steamId64 = steamId64;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getMatchId() {
        return this.matchId;
    }

    public void setMatchId(int matchId) {
        this.matchId = matchId;
    }

    public long getSteamId64() {
        return this.steamId64;
    }

    public void setSteamId64(long steamId64) {
        this.steamId64 = steamId64;
    }

}
