package com.se325.common;

import org.hibernate.annotations.Entity;

// default package
// Generated 19/09/2013 3:18:21 AM by Hibernate Tools 4.0.0

/**
 * ReplayGraph generated by hbm2java
 */

@Entity
public class ReplayGraph implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private int matchId;
    private String graphPath;

    public ReplayGraph() {
    }

    public ReplayGraph(int matchId, String graphPath) {
        this.matchId = matchId;
        this.graphPath = graphPath;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getMatchId() {
        return this.matchId;
    }

    public void setMatchId(int matchId) {
        this.matchId = matchId;
    }

    public String getGraphPath() {
        return this.graphPath;
    }

    public void setGraphPath(String graphPath) {
        this.graphPath = graphPath;
    }

}
